name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{b9a058d2-93b8-48a9-8d49-b601009f7310}}
          heroku_app_name: "blog-style-pwa"
          heroku_email: "allenlindsay812@gmail.com"